### ISSUE TITLE
Issue with CSS

### ISSUE THREAD

**Issue by erikas-tranauskas** [panteng/vue-pikaday#10]
I have one more issue with loading CSS styles. I have a custom CSS made exactly for Pikaday plugin, but there is this 'pikaday/css/pikaday.css' file import on directive file which overrides my CSS. Is it possible not to load the .css file in directive file? If someone needs the original CSS, then it should be loaded in Vue component.

**Comment by panteng** [comment]
You can increase the [specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity) of your custom styles, so your custom styles can override the styles in `pikaday.css`.

If you need more customization, you can simply copy the code inside [`directives/pikaday.js`](https://github.com/panteng/vue-pikaday/blob/master/directives/pikaday.js) to your project and treat it as your own custom directive.
