### ISSUE TITLE
Include pikaday.css directly in javascript

### ISSUE THREAD

**Issue by damienromito** [panteng/vue-pikaday#3]
I encounter that error

``` ../css/pikaday.css:1
@charset "UTF-8";
^
ParseError: Unexpected character '@'
```

 that's probably why I don't really understand how it is possible to include css file from the pikaday module directly in the javascript file

```
require('pikaday/css/pikaday.css')
```

How it is possible and why I have that error?

**Comment by panteng** [comment]
Hi.

You need to make sure you have installed `css-loader` and `style-loader` and use `Webpack` as your build tool. (See my package.json file - devDependencies)

When using `Webpack`, `css-loader` and `style-loader` make it possible to include css file in your javascript.

If you haven't used `Webpack` before, you may learn how to use it first.

**Comment by panteng** [comment]
If you don't use webpack, feel free to include the css file in the traditional way in your index.html.

**Comment by damienromito** [comment]
Ok sorry, that's why!  I'm using npm, I will test with both those modules...

**Comment by panteng** [comment]
@damienromito Remember both `css-loader` and `style-loader` need to be installed.
