### ISSUE TITLE
Vue 2 compatibility ? 

### ISSUE THREAD

**Issue by seuaCoder** [panteng/vue-pikaday#6]
Hi,

seems this doesn't work with vuejs 2, any plan to upgrade it ?

Thank you.

**Comment by panteng** [comment]
Thanks for your feedback, @seuaCoder.
Sorry I won't updrade this project in the near future. Because I have stopped using vue.js for a long time.
But after all, this is a simple project, you can do it yourself and make pikaday work with vue.js 2.

**Comment by seuaCoder** [comment]
Yes i will. In Vue 2 we should write a component instead of a custom directive. I will share it here when it's done.

**Comment by panteng** [comment]
Thanks!

**Comment by panteng** [comment]
https://github.com/panteng/vue-pikaday/releases/tag/v0.4.0
Vue 2 support added.
