### ISSUE TITLE
Update model after clearing input

### ISSUE THREAD

**Issue by erikas-tranauskas** [panteng/vue-pikaday#9]
Hello, I have a problem. After clearing the input (Delete or Backspace) and closing the datepicker, the value of the input returns to the last selected value. In this case I want it to be empty. Any ideas?

**Comment by panteng** [comment]
Hi @erikas-tranauskas I can't reproduce this issue. I tried it on the demo: https://panteng.github.io/vue-pikaday/, and the value of the input stays empty after clearing the input. Can you provide more details?

**Comment by erikas-tranauskas** [comment]
The value resets to the last selected date after I click form submit button. It looks like the data model just doesn't update after clicking Delete or Backspace. Also I tried to console.log the value of my model and it instantly restores to last selected date value after any action.

**Comment by panteng** [comment]
On the demo page, the `startDate` field in data is updated to an empty string after clearing the input. Could it be that some of your code is messing with the data model during form submission?

![image](https://user-images.githubusercontent.com/8369690/85281616-98302500-b48a-11ea-9d1a-733b3c55a6c6.png)

**Comment by erikas-tranauskas** [comment]
`<input v-pikaday v-model="filterValues.created_at_to" type="text" readonly="" autocomplete="off"/>
`
I use it like this. And my filterValues is:
`        private filterValues: any = {
            created_at_to: null
        }`

Now if I click the delete or backspace, all the input is cleared instantly (not by one symbol like on your example). Which version of Pikaday you are using? Currently I have updated the latest master from https://github.com/Pikaday/Pikaday.

**Comment by erikas-tranauskas** [comment]
I got it. I have a newer version of Pikaday, which has this key press checker: https://github.com/Pikaday/Pikaday/blob/master/pikaday.js#L569

And if I press backspace or delete then pikaday sets the value to null, but Vue instance doesn't get an update. Any way to fix this or I should just setup some key listeners of my own?

**Comment by panteng** [comment]
Good catch.

I don't know how to fix it at the moment. I guess this same issue will happen to keypress on the arrow keys as well. You can either disable the `keyboardInput` support of Pikaday (there's an option for it) if your project permits, or you can create your own key listeners to override Pikaday's default behaviour.
